#!/bin/sh
set -eu
case "${RENEWED_LINEAGE:-}" in
    /etc/letsencrypt/live/esim-landing.ivanzlobin.com|/etc/letsencrypt/live/esim-landing-vue.ivanzlobin.com)
        nginx -t
        systemctl reload nginx
        ;;
esac
